### ISSUE TITLE
Lab 3 - watson-pod failing to start due to missing apikey

### ISSUE THREAD

**Issue by ragamuffin-coder** [IBM/container-service-getting-started-wt#106]
I have followed the instructions for lab 3 but watson-pod fails to start after creating it with `kubectl create -f watson-deployment.yml`. The output for that pod in `kubectl get pods` is

```
watson-pod-7d6f5d8fdf-4fhzm        0/1     CrashLoopBackOff   1          12s
```

The logs show the following:

```
/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:63
        throw missingParamsError;
        ^

Error: Missing required parameters: apikey
    at Object.getMissingParams (/node_modules/ibm-cloud-sdk-core/lib/helper.js:102:11)
    at Object.validateInput (/node_modules/ibm-cloud-sdk-core/auth/utils/helpers.js:61:39)
    at new IamAuthenticator (/node_modules/ibm-cloud-sdk-core/auth/authenticators/iam-authenticator.js:47:17)
    at Object.getAuthenticatorFromEnvironment (/node_modules/ibm-cloud-sdk-core/auth/utils/get-authenticator-from-environment.js:63:29)
    at new ToneAnalyzerV3 (/node_modules/ibm-watson/tone-analyzer/v3.js:67:58)
    at Object.<anonymous> (/app.js:10:40)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
```

**Comment by ragamuffin-coder** [comment]
This pull request from a fellow git user fixes the issue: https://github.com/IBM/container-service-getting-started-wt/pull/105

**Comment by bhpratt** [comment]
Thanks - I am reviewing.

**Comment by bhpratt** [comment]
Thanks for opening the issue. Fixed by PR and tested in production: https://github.com/IBM/container-service-getting-started-wt/pull/105
