### ISSUE TITLE
Lab 3 - watson-pod fails to start due to insufficient credentials to ToneAnalyzer

### ISSUE THREAD

**Issue by hoymich** [IBM/container-service-getting-started-wt#85]
Lession 3a, step 7
kubectl apply -f watson-deployment.yml

After applying the deployment, the watson-pod fails to startup.  Looking at the log, I see this error:

Error: Insufficient credentials provided in constructor argument. Refer to the documentation for the required parameters. Common examples are username/password, api_key, and iam_access_token.
    at ToneAnalyzerV3.BaseService.initCredentials (/node_modules/watson-developer-cloud/lib/base_service.js:226:23)
    at ToneAnalyzerV3.BaseService (/node_modules/watson-developer-cloud/lib/base_service.js:69:29)
    at ToneAnalyzerV3 [as constructor] (/node_modules/watson-developer-cloud/tone-analyzer/v3-generated.js:54:28)
    at new ToneAnalyzerV3 (/node_modules/watson-developer-cloud/tone-analyzer/v3.js:37:24)

**Comment by jgarcows** [comment]
Did you confirm that a 'binding-tone' secret exists after step 3?  If the secret is named something else, you'll have to update the yaml in the next step to match.

**Comment by jgarcows** [comment]
I approved and merged your change request: https://github.com/IBM/container-service-getting-started-wt/pull/86

**Comment by jgarcows** [comment]
Tested with old and new tone analyzer services.  Closing issue.
